config:
  credentials: []
  project_repos:
    github.com/Deltares/ra2ce:
      branch: v1.0.0
      repo: https://github.com/Deltares/ra2ce
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Deltares/ra2ce git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-malachite-mist.sh
        container: qc.acc_gloppy-pear-tiger
  QC.Doc:
    repos:
      github.com/Deltares/ra2ce find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-smalt-goat.sh
        container: qc.doc_slaphappy-orange-gerbil
      github.com/Deltares/ra2ce git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-white-collie.sh
        container: qc.doc_baggy-cerise-cat
      github.com/Deltares/ra2ce markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-mustard-angora.sh
        container: qc.doc_smelly-gamboge-moth
      github.com/Deltares/ra2ce restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-magnolia-chipmunk.sh
        container: qc.doc_stealthy-wisteria-quoll
  QC.Lic:
    repos:
      github.com/Deltares/ra2ce licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-emerald-termite.sh
        container: qc.lic_stuffy-indigo-dormouse
  QC.Sec:
    repos:
      github.com/Deltares/ra2ce bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-carmine-lizard.sh
        container: qc.sec_snoopy-scarlet-newt
  QC.Sty:
    repos:
      github.com/Deltares/ra2ce flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-tangerine-deer.sh
        container: qc.sty_nerdy-fuchsia-anteater
      github.com/Deltares/ra2ce hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-magnolia-fowl.sh
        container: qc.sty_frumpy-flax-angelfish
      github.com/Deltares/ra2ce jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-bistre-bird.sh
        container: qc.sty_pokey-flax-crocodile
  QC.Uni:
    repos:
      github.com/Deltares/ra2ce pytest:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-brown-bordeaux.sh
        container: qc.uni_shabby-platinum-hedgehog
  QC.Ver:
    repos:
      github.com/Deltares/ra2ce get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-emerald-lynx.sh
        container: qc.ver_scummy-silver-chimpanzee
timeout: 5400
